import 'package:flutter/material.dart';
import 'package:flutter_app/widgets/index.dart' show AliImg, SliverHeader;
import 'package:ali_icons/ali_icons.dart';
import 'package:flutter_app/utils/index.dart' show util;

class IconsPage extends StatelessWidget {
  const IconsPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final Map<String, String> args = ModalRoute.of(context).settings.arguments;
    final Color _color = Theme.of(context).textTheme.title.color;
    return Scaffold(
      appBar: AppBar(
        title: Text(args["title"]),
        centerTitle: true,
      ),
      body: CustomScrollView(
        slivers: <Widget>[
          SliverHeader(
            title: "Cupertino 图标",
            suffix: "查看代码",
            action: () => util.pushCode("cupertino_icons"),
          ),
          SliverGrid.count(
            crossAxisCount: 6,
            children: <Widget>[
              Icon(Icons.refresh, color: _color),
              Icon(Icons.ac_unit, color: _color),
              Icon(Icons.access_alarm, color: _color),
              Icon(Icons.access_time, color: _color),
              Icon(Icons.account_box, color: _color),
              Icon(Icons.account_circle, color: _color),
              Icon(Icons.add, color: _color),
              Icon(Icons.add_call, color: _color),
              Icon(Icons.add_circle_outline, color: _color),
              Icon(Icons.add_photo_alternate, color: _color),
              Icon(Icons.airplay, color: _color),
              Icon(Icons.apps, color: _color),
              Icon(Icons.print, color: _color),
              Icon(Icons.android, color: _color),
              Icon(Icons.aspect_ratio, color: _color),
              Icon(Icons.autorenew, color: _color),
              Icon(Icons.backup, color: _color),
              Icon(Icons.bookmark_border, color: _color),
              Icon(Icons.arrow_forward, color: _color),
              Icon(Icons.arrow_forward_ios, color: _color),
              Icon(Icons.chevron_right, color: _color),
              Icon(Icons.border_color, color: _color),
              Icon(Icons.person_outline, color: _color),
              Icon(Icons.person, color: _color),
              Icon(Icons.settings, color: _color),
              Icon(Icons.star_border, color: _color),
              Icon(Icons.star, color: _color),
              Icon(Icons.location_on, color: _color),
              Icon(Icons.school, color: _color),
              Icon(Icons.favorite_border, color: _color),
              Icon(Icons.favorite, color: _color),
              Icon(Icons.my_location, color: _color),
              Icon(Icons.remove_red_eye, color: _color),
              Icon(Icons.add_shopping_cart, color: _color),
              Icon(Icons.search, color: _color),
              Icon(Icons.airplanemode_active, color: _color),
              Icon(Icons.bluetooth, color: _color),
              Icon(Icons.exit_to_app, color: _color),
              Icon(Icons.assessment, color: _color),
              Icon(Icons.attach_file, color: _color),
              Icon(Icons.flag, color: _color),
              Icon(Icons.beach_access, color: _color),
              Icon(Icons.color_lens, color: _color),
              Icon(Icons.center_focus_strong, color: _color),
              Icon(Icons.view_list, color: _color),
              Icon(Icons.volume_up, color: _color),
              Icon(Icons.vpn_key, color: _color),
              Icon(Icons.wallpaper, color: _color),
              Icon(Icons.warning, color: _color),
              Icon(Icons.web, color: _color),
              Icon(Icons.widgets, color: _color),
              Icon(Icons.zoom_in, color: _color),
              Icon(Icons.wifi, color: _color),
              Icon(Icons.zoom_out_map, color: _color),
            ],
          ),
          SliverHeader(
            title: "Iconfont 阿里图标",
            suffix: "查看代码",
            action: () => {},
          ),
          SliverGrid.count(
            crossAxisCount: 6,
            children: <Widget>[
              Icon(AliIcons.android, color: _color),
              Icon(AliIcons.android_outline, color: _color),
              Icon(AliIcons.area, color: _color),
              Icon(AliIcons.scan_ios, color: _color),
              Icon(AliIcons.scan, color: _color),
              Icon(AliIcons.paper_clip, color: _color),
              Icon(AliIcons.plane, color: _color),
              Icon(AliIcons.trash, color: _color),
              Icon(AliIcons.eye_close, color: _color),
              Icon(AliIcons.eye_open, color: _color),
              Icon(AliIcons.ios, color: _color),
              Icon(AliIcons.ios_outline, color: _color),
              Icon(AliIcons.user_outline, color: _color),
              Icon(AliIcons.pin, color: _color),
              Icon(AliIcons.news, color: _color),
              Icon(AliIcons.layout_ios, color: _color),
              Icon(AliIcons.home_ios, color: _color),
              Icon(AliIcons.about, color: _color),
              Icon(AliIcons.global, color: _color),
              Icon(AliIcons.dialog, color: _color),
              Icon(AliIcons.settings_outline, color: _color),
              Icon(AliIcons.package, color: _color),
              Icon(AliIcons.btn, color: _color),
              Icon(AliIcons.plugin_ios, color: _color),
              Icon(AliIcons.list, color: _color),
              Icon(AliIcons.select, color: _color),
              Icon(AliIcons.feedback, color: _color),
              Icon(AliIcons.click, color: _color),
              Icon(AliIcons.input, color: _color),
              Icon(AliIcons.switch_btn, color: _color),
              Icon(AliIcons.smiling_face, color: _color),
              Icon(AliIcons.txt, color: _color),
              Icon(AliIcons.plugin, color: _color),
              Icon(AliIcons.template, color: _color),
              Icon(AliIcons.component, color: _color),
              Icon(AliIcons.layout, color: _color),
              Icon(AliIcons.icon, color: _color),
              Icon(AliIcons.text, color: _color),
              Icon(AliIcons.edit, color: _color),
              Icon(AliIcons.smiling_face_outline, color: _color),
              Icon(AliIcons.camera_change, color: _color),
              Icon(AliIcons.complete, color: _color),
              Icon(AliIcons.pie_error, color: _color),
              Icon(AliIcons.sad_face, color: _color),
              Icon(AliIcons.ring_success, color: _color),
              Icon(AliIcons.coconut_tree, color: _color),
              Icon(AliIcons.completed, color: _color),
            ],
          ),
          SliverHeader(
            title: "Imgfont 阿里图片图标",
            suffix: "查看代码",
            action: () => util.pushCode("ali_icon"),
          ),
          SliverGrid.count(
            crossAxisCount: 5,
            children: <Widget>[
              Icon(AliImg.bike_broken, color: _color),
              Icon(AliImg.stamp_failed, color: _color),
              Icon(AliImg.circle_403, color: _color),
              Icon(AliImg.hill_404_blue, color: _color),
              Icon(AliImg.page_error, color: _color),
              Icon(AliImg.moon_404, color: _color),
              Icon(AliImg.moon_500, color: _color),
              Icon(AliImg.moon_403, color: _color),
              Icon(AliImg.building_500, color: _color),
              Icon(AliImg.box_500, color: _color),
              Icon(AliImg.box_401, color: _color),
              Icon(AliImg.gear_500, color: _color),
              Icon(AliImg.box_404, color: _color),
              Icon(AliImg.star_500, color: _color),
              Icon(AliImg.star_403, color: _color),
              Icon(AliImg.star_404, color: _color),
              Icon(AliImg.women_403, color: _color),
              Icon(AliImg.balloon_yellow, color: _color),
              Icon(AliImg.hill_404, color: _color),
              Icon(AliImg.sun_404, color: _color),
              Icon(AliImg.status_code, color: _color),
              Icon(AliImg.rocket_img, color: _color),
              Icon(AliImg.info_404, color: _color),
              Icon(AliImg.face_500, color: _color),
              Icon(AliImg.face_404, color: _color),
              Icon(AliImg.page_broken, color: _color),
              Icon(AliImg.whale_500, color: _color),
              Icon(AliImg.code_500, color: _color),
              Icon(AliImg.page_exception, color: _color),
              Icon(AliImg.satellite_404, color: _color),
              Icon(AliImg.circle_401, color: _color),
              Icon(AliImg.earth_plug_off, color: _color),
              Icon(AliImg.man_500, color: _color),
              Icon(AliImg.compute_questioon, color: _color),
              Icon(AliImg.circle_warning, color: _color),
              Icon(AliImg.ufo_discon, color: _color),
              Icon(AliImg.stamp_exception, color: _color),
              Icon(AliImg.signal_off, color: _color),
              Icon(AliImg.ship_500, color: _color),
              Icon(AliImg.block_smile, color: _color),
              Icon(AliImg.fail, color: _color),
              Icon(AliImg.face_wronged, color: _color),
              Icon(AliImg.face_cry, color: _color),
              Icon(AliImg.yellow_404, color: _color),
              Icon(AliImg.info_500, color: _color),
              Icon(AliImg.line_404, color: _color),
              Icon(AliImg.stamp_completed, color: _color),
              Icon(AliImg.man_404, color: _color),
            ],
          ),
        ],
      ),
    );
  }
}
